/** Additional curated products for expanded categories */
module.exports = [
  // ── Smart Watches (6) ──────────────────────────────────
  {
    name: 'Fitness Smart Watch Pro AMOLED',
    description: 'AMOLED display smartwatch with heart-rate, SpO2, sleep tracking, and 110+ sport modes. 7-day battery, IP68 water resistance, Bluetooth calling.',
    short_description: 'AMOLED fitness watch with health tracking & BT calls.',
    price: 8999, compare_price: 12999, brand: 'WatchTech',
    category: 'Smart Watches', device_compatibility: ['Universal'],
    tags: ['smartwatch', 'fitness', 'amoled', 'health'],
    thumbnail: 'https://images.unsplash.com/photo-1523275335684-378980b3693b?auto=format&fit=crop&w=900&q=80',
    images: ['https://images.unsplash.com/photo-1523275335684-378980b3693b?auto=format&fit=crop&w=1200&q=80'],
    affiliate_link: 'https://www.daraz.pk', affiliate_platform: 'Daraz',
    ratings_avg: 4.7, reviews_count: 186, is_featured: true, stock_status: 'In Stock',
  },
  {
    name: 'Ultra Slim Smart Band 2',
    description: 'Lightweight smart band with always-on display, step counter, notifications, and 14-day battery. Comfortable silicone strap for all-day wear.',
    short_description: 'Slim smart band with 14-day battery.',
    price: 3499, compare_price: 4999, brand: 'BandFit',
    category: 'Smart Watches', device_compatibility: ['Universal'],
    tags: ['smart band', 'fitness', 'notifications'],
    thumbnail: 'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?auto=format&fit=crop&w=900&q=80',
    images: ['https://images.unsplash.com/photo-1579586337278-3befd40fd17a?auto=format&fit=crop&w=1200&q=80'],
    affiliate_link: 'https://www.daraz.pk', affiliate_platform: 'Daraz',
    ratings_avg: 4.5, reviews_count: 142, is_featured: false, stock_status: 'In Stock',
  },
  {
    name: 'Rugged Outdoor GPS Watch',
    description: 'Military-spec GPS watch with compass, altimeter, barometer, and dual-band positioning. 50m waterproof, ideal for hiking and trekking.',
    short_description: 'Rugged GPS watch for outdoor adventures.',
    price: 12499, compare_price: 16999, brand: 'TrailGear',
    category: 'Smart Watches', device_compatibility: ['Universal'],
    tags: ['gps', 'outdoor', 'rugged', 'hiking'],
    thumbnail: 'https://images.unsplash.com/photo-1434493789847-2f02dc6ca35d?auto=format&fit=crop&w=900&q=80',
    images: ['https://images.unsplash.com/photo-1434493789847-2f02dc6ca35d?auto=format&fit=crop&w=1200&q=80'],
    affiliate_link: 'https://www.daraz.pk', affiliate_platform: 'Daraz',
    ratings_avg: 4.8, reviews_count: 67, is_featured: true, stock_status: 'Limited',
  },
  {
    name: 'Kids Safe Smart Watch with SOS',
    description: 'Child-friendly smartwatch with GPS location, SOS button, safe zone alerts, and two-way calling. Durable case with fun interchangeable straps.',
    short_description: 'Kids GPS watch with SOS & safe zones.',
    price: 5999, compare_price: 8500, brand: 'KidSafe',
    category: 'Smart Watches', device_compatibility: ['Universal'],
    tags: ['kids', 'gps', 'sos', 'safety'],
    thumbnail: 'https://images.unsplash.com/photo-1508685098649-7c20685b81c8?auto=format&fit=crop&w=900&q=80',
    images: ['https://images.unsplash.com/photo-1508685098649-7c20685b81c8?auto=format&fit=crop&w=1200&q=80'],
    affiliate_link: 'https://www.daraz.pk', affiliate_platform: 'Daraz',
    ratings_avg: 4.4, reviews_count: 88, is_featured: false, stock_status: 'In Stock',
  },
  {
    name: 'Classic Hybrid Analog Smart Watch',
    description: 'Stainless steel hybrid watch with analog hands plus smart notifications, activity tracking, and 30-day battery. Works with iOS and Android.',
    short_description: 'Hybrid analog smartwatch, 30-day battery.',
    price: 10999, compare_price: 14999, brand: 'ClassicTime',
    category: 'Smart Watches', device_compatibility: ['iPhone', 'Android'],
    tags: ['hybrid', 'analog', 'stainless', 'classic'],
    thumbnail: 'https://images.unsplash.com/photo-1522312340185-e585b57a0bb6?auto=format&fit=crop&w=900&q=80',
    images: ['https://images.unsplash.com/photo-1522312340185-e585b57a0bb6?auto=format&fit=crop&w=1200&q=80'],
    affiliate_link: 'https://www.daraz.pk', affiliate_platform: 'Daraz',
    ratings_avg: 4.6, reviews_count: 54, is_featured: false, stock_status: 'In Stock',
  },
  {
    name: 'Square Display Smart Watch S9 Style',
    description: 'Large square display with customizable watch faces, NFC payments, voice assistant, and magnetic charging. Premium aluminum frame.',
    short_description: 'Square smartwatch with NFC & voice assistant.',
    price: 7499, compare_price: 9999, brand: 'SquareTech',
    category: 'Smart Watches', device_compatibility: ['Universal'],
    tags: ['square', 'nfc', 'voice', 'premium'],
    thumbnail: 'https://images.unsplash.com/photo-1544112474-2cdc81a5c677?auto=format&fit=crop&w=900&q=80',
    images: ['https://images.unsplash.com/photo-1544112474-2cdc81a5c677?auto=format&fit=crop&w=1200&q=80'],
    affiliate_link: 'https://www.daraz.pk', affiliate_platform: 'Daraz',
    ratings_avg: 4.5, reviews_count: 201, is_featured: true, stock_status: 'In Stock',
  },

  // ── Speakers (6) ─────────────────────────────────────────
  {
    name: 'Portable Bluetooth Speaker 40W Bass',
    description: 'Waterproof IPX7 portable speaker with 40W output, deep bass radiator, and 24-hour playtime. TWS pairing for stereo sound.',
    short_description: '40W waterproof portable speaker, 24hr battery.',
    price: 4999, compare_price: 6999, brand: 'BoomBox',
    category: 'Speakers', device_compatibility: ['Universal'],
    tags: ['bluetooth', 'portable', 'waterproof', 'bass'],
    thumbnail: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=900&q=80',
    images: ['https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=1200&q=80'],
    affiliate_link: 'https://www.daraz.pk', affiliate_platform: 'Daraz',
    ratings_avg: 4.7, reviews_count: 312, is_featured: true, stock_status: 'In Stock',
  },
  {
    name: 'Mini Pocket Speaker with Carabiner',
    description: 'Ultra-compact speaker clips to your bag. Surprisingly loud 8W driver, built-in mic for calls, and USB-C charging.',
    short_description: 'Compact clip-on speaker with built-in mic.',
    price: 1499, compare_price: 2299, brand: 'PocketSound',
    category: 'Speakers', device_compatibility: ['Universal'],
    tags: ['mini', 'portable', 'clip', 'travel'],
    thumbnail: 'https://images.unsplash.com/photo-1545454679-3531b543cbeb?auto=format&fit=crop&w=900&q=80',
    images: ['https://images.unsplash.com/photo-1545454679-3531b543cbeb?auto=format&fit=crop&w=1200&q=80'],
    affiliate_link: 'https://www.daraz.pk', affiliate_platform: 'Daraz',
    ratings_avg: 4.3, reviews_count: 178, is_featured: false, stock_status: 'In Stock',
  },
  {
    name: 'RGB Party Speaker with LED Lights',
    description: '360° party speaker with synchronized RGB lights, 60W peak power, karaoke mic input, and remote control. Perfect for events.',
    short_description: 'RGB party speaker with karaoke mic input.',
    price: 8999, compare_price: 12500, brand: 'PartyBeat',
    category: 'Speakers', device_compatibility: ['Universal'],
    tags: ['rgb', 'party', 'karaoke', 'led'],
    thumbnail: 'https://images.unsplash.com/photo-1545454679-3531b543cbeb?auto=format&fit=crop&w=900&q=82',
    images: ['https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=1200&q=80'],
    affiliate_link: 'https://www.daraz.pk', affiliate_platform: 'Daraz',
    ratings_avg: 4.6, reviews_count: 95, is_featured: true, stock_status: 'In Stock',
  },
  {
    name: 'Smart Home WiFi Speaker Assistant',
    description: 'Voice-controlled WiFi speaker with multi-room audio, streaming apps support, and smart home hub compatibility.',
    short_description: 'WiFi smart speaker with voice control.',
    price: 6499, compare_price: 8999, brand: 'HomeAudio',
    category: 'Speakers', device_compatibility: ['Universal'],
    tags: ['wifi', 'smart home', 'voice', 'streaming'],
    thumbnail: 'https://images.unsplash.com/photo-1545454679-3531b543cbeb?auto=format&fit=crop&w=900&q=80',
    images: ['https://images.unsplash.com/photo-1545454679-3531b543cbeb?auto=format&fit=crop&w=1200&q=80'],
    affiliate_link: 'https://www.daraz.pk', affiliate_platform: 'Daraz',
    ratings_avg: 4.5, reviews_count: 64, is_featured: false, stock_status: 'In Stock',
  },
  {
    name: 'Desktop PC Soundbar USB',
    description: 'Slim USB soundbar for monitors and laptops. Dual drivers with clear mids, dedicated volume knob, and plug-and-play setup.',
    short_description: 'USB desktop soundbar for PC & laptop.',
    price: 2799, compare_price: 3999, brand: 'DeskSound',
    category: 'Speakers', device_compatibility: ['Universal'],
    tags: ['soundbar', 'desktop', 'usb', 'pc'],
    thumbnail: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=900&q=80',
    images: ['https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=1200&q=80'],
    affiliate_link: 'https://www.daraz.pk', affiliate_platform: 'Daraz',
    ratings_avg: 4.4, reviews_count: 121, is_featured: false, stock_status: 'In Stock',
  },
  {
    name: 'Outdoor Camping Speaker Solar',
    description: 'Rugged outdoor speaker with solar charging panel, power bank function, FM radio, and emergency flashlight. IPX6 rated.',
    short_description: 'Solar outdoor speaker with power bank.',
    price: 5599, compare_price: 7999, brand: 'CampSound',
    category: 'Speakers', device_compatibility: ['Universal'],
    tags: ['camping', 'solar', 'outdoor', 'power bank'],
    thumbnail: 'https://images.unsplash.com/photo-1545454679-3531b543cbeb?auto=format&fit=crop&w=900&q=80',
    images: ['https://images.unsplash.com/photo-1545454679-3531b543cbeb?auto=format&fit=crop&w=1200&q=80'],
    affiliate_link: 'https://www.daraz.pk', affiliate_platform: 'Daraz',
    ratings_avg: 4.6, reviews_count: 47, is_featured: false, stock_status: 'In Stock',
  },

  // ── Headphones (6) ───────────────────────────────────────
  {
    name: 'Over-Ear ANC Headphones Studio',
    description: 'Premium over-ear headphones with hybrid ANC, 40mm drivers, 50-hour battery, and multipoint Bluetooth 5.3.',
    short_description: 'Over-ear ANC headphones, 50hr battery.',
    price: 12999, compare_price: 17999, brand: 'SoundMax',
    category: 'Headphones', device_compatibility: ['Universal'],
    tags: ['over-ear', 'anc', 'bluetooth', 'studio'],
    thumbnail: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=900&q=80',
    images: ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=1200&q=80'],
    affiliate_link: 'https://www.daraz.pk', affiliate_platform: 'Daraz',
    ratings_avg: 4.8, reviews_count: 267, is_featured: true, stock_status: 'In Stock',
  },
  {
    name: 'Foldable Travel Headphones',
    description: 'Lightweight foldable on-ear headphones with soft ear cushions, inline mic, and 3.5mm + Bluetooth dual mode.',
    short_description: 'Foldable travel headphones, wired & wireless.',
    price: 3999, compare_price: 5500, brand: 'TravelTune',
    category: 'Headphones', device_compatibility: ['Universal'],
    tags: ['foldable', 'travel', 'on-ear', 'dual mode'],
    thumbnail: 'https://images.unsplash.com/photo-1484704849700-f032a568e944?auto=format&fit=crop&w=900&q=80',
    images: ['https://images.unsplash.com/photo-1484704849700-f032a568e944?auto=format&fit=crop&w=1200&q=80'],
    affiliate_link: 'https://www.daraz.pk', affiliate_platform: 'Daraz',
    ratings_avg: 4.4, reviews_count: 134, is_featured: false, stock_status: 'In Stock',
  },
  {
    name: 'Gaming Headset 7.1 Surround USB',
    description: 'RGB gaming headset with virtual 7.1 surround, detachable noise-canceling mic, and memory foam ear cups for long sessions.',
    short_description: 'RGB gaming headset with 7.1 surround.',
    price: 5499, compare_price: 7500, brand: 'GameSound',
    category: 'Headphones', device_compatibility: ['PC', 'PlayStation', 'Xbox'],
    tags: ['gaming', '7.1', 'rgb', 'headset'],
    thumbnail: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=900&q=80',
    images: ['https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=1200&q=80'],
    affiliate_link: 'https://www.daraz.pk', affiliate_platform: 'Daraz',
    ratings_avg: 4.7, reviews_count: 198, is_featured: true, stock_status: 'In Stock',
  },
  {
    name: 'Kids Safe Volume-Limit Headphones',
    description: 'Wired kids headphones with 85dB volume limit, adjustable headband, and tangle-free cable. Fun color options.',
    short_description: 'Kids headphones with safe volume limit.',
    price: 1999, compare_price: 2999, brand: 'KidTune',
    category: 'Headphones', device_compatibility: ['Universal'],
    tags: ['kids', 'safe volume', 'wired'],
    thumbnail: 'https://images.unsplash.com/photo-1484704849700-f032a568e944?auto=format&fit=crop&w=900&q=80',
    images: ['https://images.unsplash.com/photo-1484704849700-f032a568e944?auto=format&fit=crop&w=1200&q=80'],
    affiliate_link: 'https://www.daraz.pk', affiliate_platform: 'Daraz',
    ratings_avg: 4.5, reviews_count: 76, is_featured: false, stock_status: 'In Stock',
  },
  {
    name: 'Open-Ear Air Conduction Headphones',
    description: 'Open-ear design keeps you aware of surroundings while enjoying music. IPX5 sweat-proof for running and cycling.',
    short_description: 'Open-ear air conduction sports headphones.',
    price: 6999, compare_price: 9999, brand: 'AirSound',
    category: 'Headphones', device_compatibility: ['Universal'],
    tags: ['open-ear', 'sports', 'running', 'ipx5'],
    thumbnail: 'https://images.unsplash.com/photo-1572569511254-d8f925fe2cbb?auto=format&fit=crop&w=900&q=80',
    images: ['https://images.unsplash.com/photo-1572569511254-d8f925fe2cbb?auto=format&fit=crop&w=1200&q=80'],
    affiliate_link: 'https://www.daraz.pk', affiliate_platform: 'Daraz',
    ratings_avg: 4.6, reviews_count: 89, is_featured: false, stock_status: 'In Stock',
  },
  {
    name: 'Wired Studio Monitor Headphones',
    description: 'Flat-response wired headphones for mixing and content creation. Detachable cable, swivel ear cups, and included adapter.',
    short_description: 'Studio monitor headphones for creators.',
    price: 4499, compare_price: 6200, brand: 'StudioPro',
    category: 'Headphones', device_compatibility: ['Universal'],
    tags: ['studio', 'wired', 'monitor', 'creator'],
    thumbnail: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=900&q=80',
    images: ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=1200&q=80'],
    affiliate_link: 'https://www.daraz.pk', affiliate_platform: 'Daraz',
    ratings_avg: 4.7, reviews_count: 112, is_featured: true, stock_status: 'In Stock',
  },

  // ── Power Banks (6) ──────────────────────────────────────
  {
    name: '20000mAh PD Power Bank Fast Charge',
    description: 'High-capacity 20000mAh power bank with 65W USB-C PD, dual outputs, and LED percentage display. Charges laptops and phones.',
    short_description: '20000mAh 65W PD power bank for laptop & phone.',
    price: 5999, compare_price: 8500, brand: 'PowerVault',
    category: 'Power Banks', device_compatibility: ['Universal'],
    tags: ['20000mah', 'pd', '65w', 'laptop'],
    thumbnail: 'https://images.unsplash.com/photo-1609096458733-95b38583ac4e?auto=format&fit=crop&w=900&q=80',
    images: ['https://images.unsplash.com/photo-1609096458733-95b38583ac4e?auto=format&fit=crop&w=1200&q=80'],
    affiliate_link: 'https://www.daraz.pk', affiliate_platform: 'Daraz',
    ratings_avg: 4.8, reviews_count: 421, is_featured: true, stock_status: 'In Stock',
  },
  {
    name: 'MagSafe Wireless Power Bank 10000mAh',
    description: 'Slim magnetic wireless power bank snaps to iPhone MagSafe. 15W wireless + 20W USB-C wired output. Pass-through charging.',
    short_description: 'MagSafe magnetic 10000mAh wireless power bank.',
    price: 4499, compare_price: 6500, brand: 'MagPower',
    category: 'Power Banks', device_compatibility: ['iPhone 12', 'iPhone 13', 'iPhone 14', 'iPhone 15'],
    tags: ['magsafe', 'wireless', '10000mah', 'slim'],
    thumbnail: 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&w=900&q=80',
    images: ['https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&w=1200&q=80'],
    affiliate_link: 'https://www.daraz.pk', affiliate_platform: 'Daraz',
    ratings_avg: 4.6, reviews_count: 198, is_featured: true, stock_status: 'In Stock',
  },
  {
    name: '5000mAh Mini Lipstick Power Bank',
    description: 'Pocket-sized 5000mAh emergency charger. Matte finish, keychain loop, and single USB-C port. Perfect backup for daily carry.',
    short_description: 'Mini 5000mAh emergency lipstick power bank.',
    price: 1299, compare_price: 1999, brand: 'MiniVolt',
    category: 'Power Banks', device_compatibility: ['Universal'],
    tags: ['mini', 'portable', '5000mah', 'emergency'],
    thumbnail: 'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?auto=format&fit=crop&w=900&q=80',
    images: ['https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?auto=format&fit=crop&w=1200&q=80'],
    affiliate_link: 'https://www.daraz.pk', affiliate_platform: 'Daraz',
    ratings_avg: 4.3, reviews_count: 256, is_featured: false, stock_status: 'In Stock',
  },
  {
    name: '30000mAh Solar Power Bank Rugged',
    description: 'Massive 30000mAh capacity with solar panel, built-in flashlight, and IP67 rugged shell. 4 output ports for group charging.',
    short_description: '30000mAh solar rugged power bank.',
    price: 8999, compare_price: 12999, brand: 'SolarCell',
    category: 'Power Banks', device_compatibility: ['Universal'],
    tags: ['solar', '30000mah', 'rugged', 'camping'],
    thumbnail: 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&w=900&q=80',
    images: ['https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&w=1200&q=80'],
    affiliate_link: 'https://www.daraz.pk', affiliate_platform: 'Daraz',
    ratings_avg: 4.5, reviews_count: 87, is_featured: false, stock_status: 'In Stock',
  },
  {
    name: 'Built-in Cable Power Bank 10000mAh',
    description: '10000mAh power bank with integrated USB-C and Lightning cables. No extra cables needed — grab and charge.',
    short_description: '10000mAh power bank with built-in cables.',
    price: 2999, compare_price: 4200, brand: 'CableBank',
    category: 'Power Banks', device_compatibility: ['Universal'],
    tags: ['built-in cable', '10000mah', 'travel'],
    thumbnail: 'https://images.unsplash.com/photo-1609096458733-95b38583ac4e?auto=format&fit=crop&w=900&q=80',
    images: ['https://images.unsplash.com/photo-1609096458733-95b38583ac4e?auto=format&fit=crop&w=1200&q=80'],
    affiliate_link: 'https://www.daraz.pk', affiliate_platform: 'Daraz',
    ratings_avg: 4.6, reviews_count: 173, is_featured: false, stock_status: 'In Stock',
  },
  {
    name: 'Dual Wireless Pad Power Bank 15000mAh',
    description: 'Charge two phones wirelessly at once. 15000mAh capacity, foldable stand, and USB-C PD input/output.',
    short_description: 'Dual wireless charging 15000mAh power bank.',
    price: 7499, compare_price: 10500, brand: 'DualCharge',
    category: 'Power Banks', device_compatibility: ['Universal'],
    tags: ['dual wireless', '15000mah', 'stand'],
    thumbnail: 'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?auto=format&fit=crop&w=900&q=80',
    images: ['https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?auto=format&fit=crop&w=1200&q=80'],
    affiliate_link: 'https://www.daraz.pk', affiliate_platform: 'Daraz',
    ratings_avg: 4.7, reviews_count: 94, is_featured: true, stock_status: 'Limited',
  },
];
